---
parser: babel-eslint
env:
  node: true
  browser: true
extends:
  - walmart/configurations/es6-node
parserOptions:
  sourceType: module
  ecmaVersion: 9
  ecmaFeatures:
    globalReturn: true
    impliedStrict: false
plugins:
  - babel
  - filenames
  - no-useless-assign
rules:
  # additional rules
  array-bracket-spacing: 2
  comma-spacing: 2
  guard-for-in: 2
  indent:
    - 2
    - 4
    - SwitchCase: 1
  linebreak-style:
    - 2
    - unix
  no-multiple-empty-lines:
    - 2
    - max: 1
      maxBOF: 0
      maxEOF: 1
  no-return-await: 2
  no-unneeded-ternary: 2
  semi:
    - 2
    - always
  space-infix-ops: 2
  strict:
    - 2
    - never
  # todo: add rule for spacing between class methods (https://github.com/eslint/eslint/issues/7356)

  # filenames
  filenames/match-exported: 0
  filenames/match-regex:
    - 2
    - "^[a-z0-9-.]+$" # allows only kebab-like-names and names.with.parts, disallows PascalCase/camelCase and snake_case
  filenames/no-index: 0

  # no-useless-assign
  no-useless-assign/no-useless-assign: 2

  # overridden
  arrow-parens:
    - 2
    - always
  brace-style:
    - 2
    - stroustrup
  comma-dangle:
    - 2
    - never
  complexity:
    - 2
    - 20
  curly:
    - 2
    - multi-line
  dot-notation:
    - 2
    - allowPattern: "^([a-z]+(_[a-z]+)+|[_A-Z0-9]+)$" #allows keys (e.g): under_score, UPPERCASE, 123, _0
  generator-star-spacing:
    - 2
    - before: true
      after: false
  key-spacing:
    - 2
    - mode: minimum
  max-len:
    - 2
    - code: 128
      ignoreTrailingComments: true
  max-params:
    - 2
    - 5
  max-statements:
    - 2
    - 20
  no-cond-assign:
    - 2
    - always
  no-magic-numbers:
    - 2
    - ignore:
        - 0
        - 1
        - 100
        - 1000
      ignoreArrayIndexes: true
  no-multi-spaces:
    - 2
    - exceptions:
        VariableDeclarator: true
  no-trailing-spaces:
    - 2
    - skipBlankLines: true
  object-curly-spacing:
    - 2
    - never
  one-var:
    - 2
    - always
  quote-props:
    - 2
    - as-needed
    - unnecessary: false
  quotes:
    - 2
    - single

  # disable
  no-mixed-requires: 0
  prefer-const: 0

  # https://github.com/eslint/eslint/issues/7565
  no-invalid-this: 0
  babel/no-invalid-this: 2
